In [ ]:
# ----------------------------------------------------------------------------------------------------------------------- #
# Márcio Campos
# ----------------------------------------------------------------------------------------------------------------------- #
# Curso de Python
# @sou.devops
# 05/Mar/2024
# ----------------------------------------------------------------------------------------------------------------------- #
# Assuntos abordados a partir desta aula :
# - Pandas // NumPy
# - Manipulação de Dados
# - Conversão de Tipos
# - Funções Nativas
# - Funções e Métodos do Pandas
# - Condicional if
# - loop for // while
# - Estrutura de correspondência Match/Case
# - Estrutura de Contexto with
# - Estrutura de exceção Try/Except
# - Manipulando Arquivos CSV, TXT, JSON, XLS
# - Função de usuário
# ----------------------------------------------------------------------------------------------------------------------- #

O Pandas é uma biblioteca de código aberto para a linguagem de programação Python, utilizada principalmente para manipulação e análise de dados. Ela fornece estruturas de dados e funções para trabalhar com dados de forma eficiente e fácil. O principal objeto do Pandas é o DataFrame, uma estrutura de dados bidimensional semelhante a uma tabela, que permite a organização e manipulação de dados de forma semelhante a uma planilha, tornando-o ideal para lidar com conjuntos de dados tabulares, como planilhas do Excel, bancos de dados SQL, arquivos CSV, TXT, Json e entre outros formatos. O Pandas é amplamente utilizado em ciência de dados, análise financeira, logistica, saúde, contabilidade, engenharia, entre outras áreas, devido à sua flexibilidade e poder de processamento de dados.

Criada por Wes McKinney em 2008 enquanto estava trabalhando na AQR Capital Management. Foi desenvolvida originalmente para atender às necessidades de manipulação e análise de dados financeiros, mas rapidamente se tornou popular em várias outras áreas devido à sua eficiência e facilidade de uso.

O Pandas é escrito principalmente em Python. No entanto, partes críticas da biblioteca, especialmente as operações de manipulação de dados, são otimizadas em C. Isso permite que o Pandas alcance uma boa eficiência computacional ao lidar com grandes conjuntos de dados.

É necessário entender que para extrair, formtar e carregar dados (ETL), além de dominio na biblioteca, seus métodos e funções, precisamos ter dominido dos fundamentos e conceitos de Python e entender a hermeneutica da formação dos dados e no mesmo nível o segmento do negócio que você vai mensurar e fundamentalmente seus dados, em muitos casos você vai ter que explorar como "arqueólogo de dados".

Ao estudar e aprofundar-se em Analise de Dados, você automaticamente precisa utilizar os recuros de Python de Fundamentos e Conceitos, bibliotecas, funções de usuário, classes, loops, condicionais, estrutura de exceção, correspondencia..

- inicio dos tempos (não existia dado)
- tempos atuais (dados em excesso)

Os dados são essenciais a qualquer empresa de qualquer porte e de qualquer segmento.

Dicas :
- Diminuir os cenários;
- Padronizar dados;
- Ferramentas e algoritmos estruturados, com maturidade;
- Estudar estruturas de dados em Python; 
- Atenção a declaração, nomenclatura e utilização das variáveis;
- Manter sempre o conjunto de dados origem intacto protegido;
- Analisar os cenários definidos;
- Teste A/B se possível;

Básico
- extrair
- transformar 
- carregar 
- seleções ou filtros 
- dicas

:: read_csv() : Para ler dados de arquivos CSV 
:: to_csv() :  Para gravar um CSV (dica planilhas grandes gerem CSV)        
:: head(), tail() : Retorna as primeiras ou últimas linhas de um DataFrame.
:: info(), describe() : Fornece informações sobre as colunas e estatísticas descritivas do DataFrame.
:: shape : Retorna o número de linhas e colunas do DataFrame.
:: drop(): Remove linhas ou colunas do DataFrame.
:: mean(), median(), sum(), std(): Calcula estatísticas resumidas.
:: sort_values() : Para classificar um DataFrame ou uma Série com base em uma ou mais colunas.
:: to_datetime(): Converte uma coluna em formato de data e hora.

In [6]:
# Instalação do Pandas
# --------------------
# pip install pandas
# !pip install pandas

import pandas as pd # (as é alias/apelido para simplificar e identificar sua utilização no módulo)

In [27]:
# Abrindo CSV
# ------------------------------------------ #

df_folha = pd.read_csv("FolhaPag.csv", delimiter=';', encoding='Windows-1252')

df_dados = df_folha 

print("   Variável df_dados : ", type(df_dados)) # tipo da variável df_dados 
print("Retorno Método shape : ", df_dados.shape) # tamanho em linhas do dataframe

print("")

print("  shape : ", type(df_dados.shape)) # resultado do método shape
print(" Linhas : ", df_dados.shape[0])    # linhas do dataframe
print("Colunas : ", df_dados.shape[1])    # colunas do dataframe

   Variável df_dados :  <class 'pandas.core.frame.DataFrame'>
Retorno Método shape :  (50000, 13)

  shape :  <class 'tuple'>
 Linhas :  50000
Colunas :  13

In [16]:
df_folha

,Unnamed: 0,Nome,Nascimento,Sal rio,Filhos,Ativo,UF,email,FGTS,13Sal,F‚rias,CestaB sica,AjudaCusto
0,0,Zacarias Vieira,30/04/1967,"6873,72",2.0,VERDADEIRO,MS,sem email,"601,4505","572,81","2291,24",450.0,0
1,1,Ana da Gomes,08/08/1966,"10744,1",5.0,VERDADEIRO,MG,sem email,"940,10875","895,3416667","3581,37",1125.0,0
2,2,Bruno Cardoso Filha,04/12/1989,"14647,7",3.0,VERDADEIRO,BA,nÆo confirmado,"1281,67375","1220,641667","4882,57",675.0,0
3,3,JoÆo Martins,22/05/1953,"7819,52",5.0,FALSO,RN,sem email,"684,208","651,6266667","2606,51",1125.0,0
4,4,Carla Martins,19/05/1984,"17444,58",0.0,FALSO,PE,sem email,"1526,40075","1453,715","5814,86",225.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49995,Marcius das Cavalcanti,20/07/1967,"17814,37",5.0,VERDADEIRO,RJ,sem email,"1558,757375","1484,530833","5938,12",1125.0,0
49996,49996,Tiago da Gon‡alves Sobrinho,18/04/1956,"17595,72",2.0,FALSO,CE,invalido,"1539,6255","1466,31","5865,24",450.0,0
49997,49997,Paulo Morais,26/09/1960,"2250,71",4.0,VERDADEIRO,RO,invalido,"196,937125","187,5591667","750,24",900.0,250
49998,49998,Fernando Ramos Filha,09/09/1971,"13120,24",0.0,VERDADEIRO,DF,sem email,"1148,021","1093,353333","4373,41",225.0,0
49999,49999,Irene da Pinto,16/02/2000,"10096,82",0.0,FALSO,TO,sem email,"883,47175","841,4016667","3365,61",225.0,0

In [9]:
df_dados.head() # apresenta as 5 primeiras linhas do dataframe

,Unnamed: 0,Nome,Nascimento,Sal rio,Filhos,Ativo,UF,email,FGTS,13Sal,F‚rias,CestaB sica,AjudaCusto
0,0,Zacarias Vieira,30/04/1967,"6873,72",2.0,VERDADEIRO,MS,sem email,"601,4505","572,81","2291,24",450.0,0
1,1,Ana da Gomes,08/08/1966,"10744,1",5.0,VERDADEIRO,MG,sem email,"940,10875","895,3416667","3581,37",1125.0,0
2,2,Bruno Cardoso Filha,04/12/1989,"14647,7",3.0,VERDADEIRO,BA,nÆo confirmado,"1281,67375","1220,641667","4882,57",675.0,0
3,3,JoÆo Martins,22/05/1953,"7819,52",5.0,FALSO,RN,sem email,"684,208","651,6266667","2606,51",1125.0,0
4,4,Carla Martins,19/05/1984,"17444,58",0.0,FALSO,PE,sem email,"1526,40075","1453,715","5814,86",225.0,0

In [10]:
df_dados.head(1000)

,Unnamed: 0,Nome,Nascimento,Sal rio,Filhos,Ativo,UF,email,FGTS,13Sal,F‚rias,CestaB sica,AjudaCusto
0,0,Zacarias Vieira,30/04/1967,"6873,72",2.0,VERDADEIRO,MS,sem email,"601,4505","572,81","2291,24",450.0,0
1,1,Ana da Gomes,08/08/1966,"10744,1",5.0,VERDADEIRO,MG,sem email,"940,10875","895,3416667","3581,37",1125.0,0
2,2,Bruno Cardoso Filha,04/12/1989,"14647,7",3.0,VERDADEIRO,BA,nÆo confirmado,"1281,67375","1220,641667","4882,57",675.0,0
3,3,JoÆo Martins,22/05/1953,"7819,52",5.0,FALSO,RN,sem email,"684,208","651,6266667","2606,51",1125.0,0
4,4,Carla Martins,19/05/1984,"17444,58",0.0,FALSO,PE,sem email,"1526,40075","1453,715","5814,86",225.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,Gisele das Barbosa Jr,15/08/1967,"11006,66",2.0,FALSO,RR,invalido,"963,08275","917,2216667","3668,89",450.0,0
996,996,Roberto Andrade Filho,01/10/1989,"13862,29",4.0,FALSO,CE,invalido,"1212,950375","1155,190833","4620,76",900.0,0
997,997,Marcius Martinez,01/08/1967,"10014,7",5.0,FALSO,SE,sem email,"876,28625","834,5583333","3338,23",1125.0,0
998,998,Carla de Morais,29/04/1978,"13647,88",2.0,VERDADEIRO,RR,sem email,"1194,1895","1137,323333","4549,29",450.0,0
999,999,Nelson Costa,07/10/1953,"7717,03",0.0,FALSO,AC,sem email,"675,240125","643,0858333","2572,34",225.0,0

In [11]:
df_dados.tail() # apresenta as 5 primeiras linhas do dataframe

,Unnamed: 0,Nome,Nascimento,Sal rio,Filhos,Ativo,UF,email,FGTS,13Sal,F‚rias,CestaB sica,AjudaCusto
49995,49995,Marcius das Cavalcanti,20/07/1967,"17814,37",5.0,VERDADEIRO,RJ,sem email,"1558,757375","1484,530833","5938,12",1125.0,0
49996,49996,Tiago da Gon‡alves Sobrinho,18/04/1956,"17595,72",2.0,FALSO,CE,invalido,"1539,6255","1466,31","5865,24",450.0,0
49997,49997,Paulo Morais,26/09/1960,"2250,71",4.0,VERDADEIRO,RO,invalido,"196,937125","187,5591667","750,24",900.0,250
49998,49998,Fernando Ramos Filha,09/09/1971,"13120,24",0.0,VERDADEIRO,DF,sem email,"1148,021","1093,353333","4373,41",225.0,0
49999,49999,Irene da Pinto,16/02/2000,"10096,82",0.0,FALSO,TO,sem email,"883,47175","841,4016667","3365,61",225.0,0

In [12]:
df_dados.tail(100)

,Unnamed: 0,Nome,Nascimento,Sal rio,Filhos,Ativo,UF,email,FGTS,13Sal,F‚rias,CestaB sica,AjudaCusto
49900,49900,Eduardo Borges,18/03/1981,"2911,99",0.0,VERDADEIRO,MG,invalido,"254,799125","242,6658333","970,66",225.0,0
49901,49901,Julio Batista Sobrinho,31/12/1970,"7833,64",1.0,FALSO,RO,sem email,"685,4435","652,8033333","2611,21",225.0,0
49902,49902,Xuxa Martins,01/06/1989,"3724,09",3.0,FALSO,MT,invalido,"325,857875","310,3408333","1241,36",675.0,0
49903,49903,Gabriel das Carneiro,21/02/1961,"5805,98",3.0,VERDADEIRO,AL,nÆo confirmado,"508,02325","483,8316667","1935,33",675.0,0
49904,49904,Natalia Andrade,23/12/1983,"8918,33",2.0,FALSO,SE,nÆo confirmado,"780,353875","743,1941667","2972,78",450.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49995,Marcius das Cavalcanti,20/07/1967,"17814,37",5.0,VERDADEIRO,RJ,sem email,"1558,757375","1484,530833","5938,12",1125.0,0
49996,49996,Tiago da Gon‡alves Sobrinho,18/04/1956,"17595,72",2.0,FALSO,CE,invalido,"1539,6255","1466,31","5865,24",450.0,0
49997,49997,Paulo Morais,26/09/1960,"2250,71",4.0,VERDADEIRO,RO,invalido,"196,937125","187,5591667","750,24",900.0,250
49998,49998,Fernando Ramos Filha,09/09/1971,"13120,24",0.0,VERDADEIRO,DF,sem email,"1148,021","1093,353333","4373,41",225.0,0
49999,49999,Irene da Pinto,16/02/2000,"10096,82",0.0,FALSO,TO,sem email,"883,47175","841,4016667","3365,61",225.0,0

In [135]:
df_dados.info() # Exibe um resumo da estrutura do seu Dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   50000 non-null  int64
 1   Nome         49969 non-null  object
 2   Nascimento   49970 non-null  object
 3   Sal rio      49972 non-null  object
 4   Filhos       49978 non-null  float64
 5   Ativo        49976 non-null  object
 6   UF           49971 non-null  object
 7   email        49964 non-null  object
 8   FGTS         49972 non-null  object
 9   13Sal        49972 non-null  object
 10  Frias       49972 non-null  object
 11  CestaB sica  49978 non-null  float64
 12  AjudaCusto   50000 non-null  int64
dtypes: float64(2), int64(2), object(9)
memory usage: 5.0+ MB

describe()

É uma ferramenta útil para obter um resumo estatístico de um DataFrame ou de uma série de dados. Quando aplicado a um DataFrame, o método describe() calcula estatísticas descritivas para cada coluna numérica no DataFrame.

Contagem (count): O número de observações não nulas em cada coluna.

Média (mean): A média aritmética dos valores em cada coluna.

Desvio Padrão (std): O desvio padrão dos valores em cada coluna, que é uma medida de dispersão que indica o quanto os valores estão distantes da média.

Valor Mínimo (min): O valor mínimo encontrado em cada coluna.

Percentil 25 (25%): Primeiro quartil dos dados, ou seja, 25% dos dados estão abaixo desse valor.
Percentil 50 (50%): Segundo quartil dos dados, ou seja, 50% dos dados estão abaixo desse valor, que é também a mediana.
Percentil 75 (75%): Terceiro quartil dos dados, ou seja, 75% dos dados estão abaixo desse valor.

Valor Máximo (max): O valor máximo encontrado em cada coluna.

Por padrão, o método describe() só considera as colunas numéricas do DataFrame. Se você quiser incluir também as colunas não numéricas (por exemplo, strings), pode usar o parâmetro include='all'.

In [136]:
df_dados.describe()

         Unnamed: 0        Filhos   CestaB sica    AjudaCusto
count  50000.000000  49978.000000  49978.000000  50000.000000
mean   24999.500000      2.506663    601.599704     16.825000
std    14433.901067      1.713125    336.461427     62.635835
min        0.000000      0.000000    225.000000      0.000000
25%    12499.750000      1.000000    225.000000      0.000000
50%    24999.500000      3.000000    675.000000      0.000000
75%    37499.250000      4.000000    900.000000      0.000000
max    49999.000000      5.000000   1125.000000    250.000000

In [13]:
df_dados.describe(include='all')

,Unnamed: 0,Nome,Nascimento,Sal rio,Filhos,Ativo,UF,email,FGTS,13Sal,F‚rias,CestaB sica,AjudaCusto
count,50000.000000,49969,49970,49972,49978.000000,49976,49971,49964,49972,49972,49972,49978.000000,50000.000000
unique,NaN,15593,17398,49283,NaN,2,27,4,49283,49283,47902,NaN,NaN
top,NaN,Fabiana Ramos,21/03/1988,"8122,61",NaN,FALSO,MS,sem email,"710,728375","676,8841667","4439,17",NaN,NaN
freq,NaN,27,12,3,NaN,25027,1911,23976,3,3,4,NaN,NaN
mean,24999.500000,NaN,NaN,NaN,2.506663,NaN,NaN,NaN,NaN,NaN,NaN,601.599704,16.825000
std,14433.901067,NaN,NaN,NaN,1.713125,NaN,NaN,NaN,NaN,NaN,NaN,336.461427,62.635835
min,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,225.000000,0.000000
25%,12499.750000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,225.000000,0.000000
50%,24999.500000,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,675.000000,0.000000
75%,37499.250000,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,900.000000,0.000000
max,49999.000000,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,1125.000000,250.000000

In [14]:
df_dados

,Unnamed: 0,Nome,Nascimento,Sal rio,Filhos,Ativo,UF,email,FGTS,13Sal,F‚rias,CestaB sica,AjudaCusto
0,0,Zacarias Vieira,30/04/1967,"6873,72",2.0,VERDADEIRO,MS,sem email,"601,4505","572,81","2291,24",450.0,0
1,1,Ana da Gomes,08/08/1966,"10744,1",5.0,VERDADEIRO,MG,sem email,"940,10875","895,3416667","3581,37",1125.0,0
2,2,Bruno Cardoso Filha,04/12/1989,"14647,7",3.0,VERDADEIRO,BA,nÆo confirmado,"1281,67375","1220,641667","4882,57",675.0,0
3,3,JoÆo Martins,22/05/1953,"7819,52",5.0,FALSO,RN,sem email,"684,208","651,6266667","2606,51",1125.0,0
4,4,Carla Martins,19/05/1984,"17444,58",0.0,FALSO,PE,sem email,"1526,40075","1453,715","5814,86",225.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49995,Marcius das Cavalcanti,20/07/1967,"17814,37",5.0,VERDADEIRO,RJ,sem email,"1558,757375","1484,530833","5938,12",1125.0,0
49996,49996,Tiago da Gon‡alves Sobrinho,18/04/1956,"17595,72",2.0,FALSO,CE,invalido,"1539,6255","1466,31","5865,24",450.0,0
49997,49997,Paulo Morais,26/09/1960,"2250,71",4.0,VERDADEIRO,RO,invalido,"196,937125","187,5591667","750,24",900.0,250
49998,49998,Fernando Ramos Filha,09/09/1971,"13120,24",0.0,VERDADEIRO,DF,sem email,"1148,021","1093,353333","4373,41",225.0,0
49999,49999,Irene da Pinto,16/02/2000,"10096,82",0.0,FALSO,TO,sem email,"883,47175","841,4016667","3365,61",225.0,0

sort_values()
Este método do Pandas é utilizado para ordenar os valores em um DataFrame ou em uma série com base nos valores de uma ou mais colunas. Ele oferece flexibilidade para ordenar os dados de maneira ascendente ou descendente.

df_dados.sort_values(by, axis=0, ascending=True, inplace=False, na_position='last', ignore_index=False, key=None)

by: Especifica a coluna ou uma lista de colunas pelas quais os dados serão ordenados. Se for uma lista de colunas, a ordenação será realizada em ordem de prioridade das colunas especificadas.

axis: Indica o eixo ao longo do qual a ordenação será realizada. Por padrão, é 0 (ou 'index'), o que significa que as linhas serão ordenadas. Se você deseja ordenar as colunas, pode definir axis=1 (ou 'columns').

ascending: Define a ordem de classificação. Se for True, os valores serão classificados em ordem ascendente (do menor para o maior). Se for False, os valores serão classificados em ordem decrescente (do maior para o menor).

inplace: Se for True, a ordenação será aplicada diretamente ao DataFrame ou à série e modifica o objeto original. Se for False (padrão), uma nova estrutura de dados será retornada com os valores ordenados.

na_position: Define o tratamento de valores NaN (dados ausentes) durante a ordenação. As opções são 'first' (coloca os NaNs no início) ou 'last' (coloca os NaNs no final).

ignore_index: Se for True, o índice resultante será redefinido para sequencialmente de 0 a n - 1, onde n é o número de linhas do DataFrame ou da série ordenada. Isso é útil quando você deseja redefinir o índice após a ordenação.

key: Função que pode ser fornecida para personalizar a comparação dos valores antes da ordenação. É útil para ordenação personalizada.

In [17]:
df_dados.head()

,Unnamed: 0,Nome,Nascimento,Sal rio,Filhos,Ativo,UF,email,FGTS,13Sal,F‚rias,CestaB sica,AjudaCusto
0,0,Zacarias Vieira,30/04/1967,"6873,72",2.0,VERDADEIRO,MS,sem email,"601,4505","572,81","2291,24",450.0,0
1,1,Ana da Gomes,08/08/1966,"10744,1",5.0,VERDADEIRO,MG,sem email,"940,10875","895,3416667","3581,37",1125.0,0
2,2,Bruno Cardoso Filha,04/12/1989,"14647,7",3.0,VERDADEIRO,BA,nÆo confirmado,"1281,67375","1220,641667","4882,57",675.0,0
3,3,JoÆo Martins,22/05/1953,"7819,52",5.0,FALSO,RN,sem email,"684,208","651,6266667","2606,51",1125.0,0
4,4,Carla Martins,19/05/1984,"17444,58",0.0,FALSO,PE,sem email,"1526,40075","1453,715","5814,86",225.0,0

In [18]:
df_dados.sort_values(by='Nome', axis=0, ascending=True, inplace=False, na_position='last', ignore_index=False, key=None)

,Unnamed: 0,Nome,Nascimento,Sal rio,Filhos,Ativo,UF,email,FGTS,13Sal,F‚rias,CestaB sica,AjudaCusto
18318,18318,Alice Almeida,11/12/1951,"18707,04",0.0,VERDADEIRO,DF,sem email,"1636,866","1558,92","6235,68",225.0,0
34164,34164,Alice Almeida,18/08/1964,"15419,94",1.0,FALSO,ES,sem email,"1349,24475","1284,995","5139,98",225.0,0
23236,23236,Alice Almeida,23/01/1968,"2854,42",0.0,VERDADEIRO,SC,sem email,"249,76175","237,8683333","951,47",225.0,0
38893,38893,Alice Almeida,28/08/1996,"6711,93",3.0,VERDADEIRO,BA,invalido,"587,293875","559,3275","2237,31",675.0,0
15730,15730,Alice Almeida,16/09/1969,"2275,93",2.0,FALSO,PR,invalido,"199,143875","189,6608333","758,64",450.0,250
...,...,...,...,...,...,...,...,...,...,...,...,...,...
36558,36558,NaN,14/09/1952,"11205,96",4.0,FALSO,PR,sem email,"980,5215","933,83","3735,32",900.0,0
41354,41354,NaN,17/03/1993,"5438,53",4.0,VERDADEIRO,SC,spamlistafirewall,"475,871375","453,2108333","1812,84",900.0,0
42355,42355,NaN,21/05/1995,"11826,77",5.0,FALSO,MS,nÆo confirmado,"1034,842375","985,5641667","3942,26",1125.0,0
43787,43787,NaN,10/03/1978,"2059,6",5.0,VERDADEIRO,AP,sem email,"180,215","171,6333333","686,53",1125.0,250
43970,43970,NaN,21/12/1975,"10641,75",0.0,FALSO,CE,nÆo confirmado,"931,153125","886,8125","3547,25",225.0,0

In [19]:
df_dados.head()

,Unnamed: 0,Nome,Nascimento,Sal rio,Filhos,Ativo,UF,email,FGTS,13Sal,F‚rias,CestaB sica,AjudaCusto
0,0,Zacarias Vieira,30/04/1967,"6873,72",2.0,VERDADEIRO,MS,sem email,"601,4505","572,81","2291,24",450.0,0
1,1,Ana da Gomes,08/08/1966,"10744,1",5.0,VERDADEIRO,MG,sem email,"940,10875","895,3416667","3581,37",1125.0,0
2,2,Bruno Cardoso Filha,04/12/1989,"14647,7",3.0,VERDADEIRO,BA,nÆo confirmado,"1281,67375","1220,641667","4882,57",675.0,0
3,3,JoÆo Martins,22/05/1953,"7819,52",5.0,FALSO,RN,sem email,"684,208","651,6266667","2606,51",1125.0,0
4,4,Carla Martins,19/05/1984,"17444,58",0.0,FALSO,PE,sem email,"1526,40075","1453,715","5814,86",225.0,0

In [20]:
df_dados.sort_values(by='Nome', axis=0, ascending=True, inplace=True, na_position='last', ignore_index=False, key=None)

In [21]:
df_dados.head(100)

,Unnamed: 0,Nome,Nascimento,Sal rio,Filhos,Ativo,UF,email,FGTS,13Sal,F‚rias,CestaB sica,AjudaCusto
18318,18318,Alice Almeida,11/12/1951,"18707,04",0.0,VERDADEIRO,DF,sem email,"1636,866","1558,92","6235,68",225.0,0
34164,34164,Alice Almeida,18/08/1964,"15419,94",1.0,FALSO,ES,sem email,"1349,24475","1284,995","5139,98",225.0,0
23236,23236,Alice Almeida,23/01/1968,"2854,42",0.0,VERDADEIRO,SC,sem email,"249,76175","237,8683333","951,47",225.0,0
38893,38893,Alice Almeida,28/08/1996,"6711,93",3.0,VERDADEIRO,BA,invalido,"587,293875","559,3275","2237,31",675.0,0
15730,15730,Alice Almeida,16/09/1969,"2275,93",2.0,FALSO,PR,invalido,"199,143875","189,6608333","758,64",450.0,250
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5608,5608,Alice Borges,24/12/1967,9210,0.0,FALSO,MS,nÆo confirmado,"805,875","767,5",3070,225.0,0
41925,41925,Alice Campos,06/10/1960,"16245,02",5.0,FALSO,RN,invalido,"1421,43925","1353,751667","5415,01",1125.0,0
24293,24293,Alice Campos,16/11/1998,"12828,12",2.0,VERDADEIRO,AP,sem email,"1122,4605","1069,01","4276,04",450.0,0
41543,41543,Alice Campos,22/03/1976,"16319,84",1.0,VERDADEIRO,TO,invalido,"1427,986","1359,986667","5439,95",225.0,0
17323,17323,Alice Campos,13/10/1970,"13177,03",3.0,VERDADEIRO,RR,invalido,"1152,990125","1098,085833","4392,34",675.0,0

In [5]:
df_dados_ordem = df_dados.sort_values(by='Nome', ascending=True)

In [22]:
df_dados_ordem.head()

,Unnamed: 0,Nome,Nascimento,Sal rio,Filhos,Ativo,UF,email,FGTS,13Sal,F‚rias,CestaB sica,AjudaCusto
18318,18318,Alice Almeida,11/12/1951,"18707,04",0.0,VERDADEIRO,DF,sem email,"1636,866","1558,92","6235,68",225.0,0
34164,34164,Alice Almeida,18/08/1964,"15419,94",1.0,FALSO,ES,sem email,"1349,24475","1284,995","5139,98",225.0,0
23236,23236,Alice Almeida,23/01/1968,"2854,42",0.0,VERDADEIRO,SC,sem email,"249,76175","237,8683333","951,47",225.0,0
38893,38893,Alice Almeida,28/08/1996,"6711,93",3.0,VERDADEIRO,BA,invalido,"587,293875","559,3275","2237,31",675.0,0
15730,15730,Alice Almeida,16/09/1969,"2275,93",2.0,FALSO,PR,invalido,"199,143875","189,6608333","758,64",450.0,250

In [24]:
df_folha.head()

,Unnamed: 0,Nome,Nascimento,Sal rio,Filhos,Ativo,UF,email,FGTS,13Sal,F‚rias,CestaB sica,AjudaCusto
18318,18318,Alice Almeida,11/12/1951,"18707,04",0.0,VERDADEIRO,DF,sem email,"1636,866","1558,92","6235,68",225.0,0
34164,34164,Alice Almeida,18/08/1964,"15419,94",1.0,FALSO,ES,sem email,"1349,24475","1284,995","5139,98",225.0,0
23236,23236,Alice Almeida,23/01/1968,"2854,42",0.0,VERDADEIRO,SC,sem email,"249,76175","237,8683333","951,47",225.0,0
38893,38893,Alice Almeida,28/08/1996,"6711,93",3.0,VERDADEIRO,BA,invalido,"587,293875","559,3275","2237,31",675.0,0
15730,15730,Alice Almeida,16/09/1969,"2275,93",2.0,FALSO,PR,invalido,"199,143875","189,6608333","758,64",450.0,250

O "encoding" (codificação) em computação se refere ao método usado para representar caracteres de texto em binário. Isso é importante porque diferentes sistemas e arquivos podem usar diferentes conjuntos de caracteres e, portanto, exigem codificações diferentes para interpretar corretamente os dados de texto.

Existem várias codificações comuns, como UTF-8, UTF-16, ISO-8859-1 (também conhecido como Latin-1), entre outras. Cada uma dessas codificações representa caracteres de texto de maneira diferente.

In [26]:
import chardet

nome_arquivo = "FolhaPag.csv"

# Estrutura de contexto
# ---------------------
with open(nome_arquivo, 'rb') as f:
    resultado = chardet.detect(f.read())
    

# Exibe a codificação detectada
# -----------------------------
print("Codificação detectada:", resultado['encoding'])

Codificação detectada: Windows-1252

Importante ter como premissa : Todas bibliotecas, funções/métodos no Python tem sua devida documentação a ser explorada, estudada, analisada e testada, existe recurso, você pode dominar. Não pense em decorar, é perda de tempo, pense em acessar, ler e utilizar.

Leitura e Escrita de Dados:
read_csv(), read_excel(), read_sql(): Para ler dados de arquivos CSV, Excel, ou de bancos de dados SQL, respectivamente.
to_csv(), to_excel(), to_sql(): Para escrever dados em arquivos CSV, Excel ou bancos de dados SQL.
Manipulação de DataFrames:


loc[], iloc[]: Para acessar linhas e colunas baseadas em rótulos ou índices.
fillna(), dropna(): Preenche ou remove valores ausentes (NaN) do DataFrame.
merge(), concat(): Para combinar DataFrames.

Operações de Transformação:

apply(): Aplica uma função a cada elemento do DataFrame.
groupby(), agg(): Agrupa dados com base em uma ou mais colunas e permite operações agregadas.
pivot_table(): Cria uma tabela dinâmica a partir de um DataFrame.
Operações Estatísticas:


corr(), cov(): Calcula a correlação e a covariância entre as colunas.
value_counts(): Conta os valores únicos em uma coluna.
Visualização de Dados:

plot(): Plota os dados.
hist(), boxplot(): Cria histogramas e gráficos de caixa para análise exploratória.
Trabalhando com Séries Temporais:

to_datetime(): Converte uma coluna em formato de data e hora.