In [ ]:
# -----------------------------------------------------------------------------------------------------------------------+
# Márcio Campos                                                                                                          +
# -----------------------------------------------------------------------------------------------------------------------+
# Curso de Python                                                                                                        +
# @sou.devops                                                                                                            +
# 19/Mar/2024                                                                                                            +                                                                                                         
# -----------------------------------------------------------------------------------------------------------------------+
# Lógica no raciocinio do tratamento da base                                                                             +
# Filtrar a base de dados                                                                                                +
# Exportar a base tratada                                                                                                +
# -----------------------------------------------------------------------------------------------------------------------+ 
# Dados Estruturado x Dados não estruturados                                                                             +
# -----------------------------------------------------------------------------------------------------------------------+

<div style="color: red; font-weight: bold; font-size: 24px; line-height: 1.5;">
ETL(Extract / Transform / Load)
</div>

<div style="color: green; font-size: 14px; line-height: 1.5;">
Pandas<br>
@sou.devops
</div>

In [174]:
import pandas as pd
import numpy  as np
import re

df_dados = pd.read_csv("FolhaPag.csv", delimiter=';', encoding='Windows-1252')

df_folha = df_dados.copy()

In [178]:
df_folha.head(200)

,Indice,Nome,Nascimento,Salï¿½rio,Filhos,Ativo,UF,email,FGTS,13Sal,Fï¿½rias,CestaBï¿½sica,AjudaCusto
0,0,Zacarias Vieira,30/04/1967,"6873,72",2.0,VERDADEIRO,MS,sem email,"601,4505","572,81","2291,24",450.0,0
1,1,Ana da Gomes,08/08/1966,"10744,1",5.0,VERDADEIRO,MG,sem email,"940,10875","895,3416667","3581,37",1125.0,0
2,2,Bruno Cardoso Filha,04/12/1989,"14647,7",3.0,VERDADEIRO,BA,nï¿½o confirmado,"1281,67375","1220,641667","4882,57",675.0,0
3,3,Joï¿½o Martins,22/05/1953,"7819,52",5.0,FALSO,RN,sem email,"684,208","651,6266667","2606,51",1125.0,0
4,4,Carla Martins,19/05/1984,"17444,58",0.0,FALSO,PE,sem email,"1526,40075","1453,715","5814,86",225.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,195,Roberto dos Ribeiro,24/04/1988,"5108,4",1.0,FALSO,TO,sem email,"446,985","425,7","1702,8",225.0,0
196,196,Bruno Rodrigues,31/07/1953,"12528,42",2.0,VERDADEIRO,DF,sem email,"1096,23675","1044,035","4176,14",450.0,0
197,197,Fernando dos Morais,02/02/1964,"13205,24",4.0,VERDADEIRO,PE,sem email,"1155,4585","1100,436667","4401,75",900.0,0
198,198,Sofia das Castro,07/05/1978,"14534,51",3.0,VERDADEIRO,RN,sem email,"1271,769625","1211,209167","4844,84",675.0,0
199,199,Alice Carvalho,21/12/1960,"14426,1",0.0,VERDADEIRO,MG,sem email,"1262,28375","1202,175","4808,7",225.0,0

In [179]:
df_folha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Indice         50000 non-null  int64
 1   Nome           49969 non-null  object
 2   Nascimento     49970 non-null  object
 3   Salï¿½rio      49972 non-null  object
 4   Filhos         49978 non-null  float64
 5   Ativo          49976 non-null  object
 6   UF             49971 non-null  object
 7   email          49964 non-null  object
 8   FGTS           49972 non-null  object
 9   13Sal          49972 non-null  object
 10  Fï¿½rias       49972 non-null  object
 11  CestaBï¿½sica  49978 non-null  float64
 12  AjudaCusto     50000 non-null  int64
dtypes: float64(2), int64(2), object(9)
memory usage: 5.0+ MB

In [72]:
df_folha.head()

,Indice,Nome,Nascimento,Salï¿½rio,Filhos,Ativo,UF,email,FGTS,13Sal,Fï¿½rias,CestaBï¿½sica,AjudaCusto
0,0,Zacarias Vieira,30/04/1967,"6873,72",2.0,VERDADEIRO,MS,sem email,"601,4505","572,81","2291,24",450.0,0
1,1,Ana da Gomes,08/08/1966,"10744,1",5.0,VERDADEIRO,MG,sem email,"940,10875","895,3416667","3581,37",1125.0,0
2,2,Bruno Cardoso Filha,04/12/1989,"14647,7",3.0,VERDADEIRO,BA,nï¿½o confirmado,"1281,67375","1220,641667","4882,57",675.0,0
3,3,Joï¿½o Martins,22/05/1953,"7819,52",5.0,FALSO,RN,sem email,"684,208","651,6266667","2606,51",1125.0,0
4,4,Carla Martins,19/05/1984,"17444,58",0.0,FALSO,PE,sem email,"1526,40075","1453,715","5814,86",225.0,0

In [180]:
df_folha.describe()

             Indice        Filhos  CestaBï¿½sica    AjudaCusto
count  50000.000000  49978.000000   49978.000000  50000.000000
mean   24999.500000      2.506663     601.599704     16.825000
std    14433.901067      1.713125     336.461427     62.635835
min        0.000000      0.000000     225.000000      0.000000
25%    12499.750000      1.000000     225.000000      0.000000
50%    24999.500000      3.000000     675.000000      0.000000
75%    37499.250000      4.000000     900.000000      0.000000
max    49999.000000      5.000000    1125.000000    250.000000

In [181]:
df_folha.describe(include='all')

,Indice,Nome,Nascimento,Salï¿½rio,Filhos,Ativo,UF,email,FGTS,13Sal,Fï¿½rias,CestaBï¿½sica,AjudaCusto
count,50000.000000,49969,49970,49972,49978.000000,49976,49971,49964,49972,49972,49972,49978.000000,50000.000000
unique,NaN,15593,17398,49283,NaN,2,27,4,49283,49283,47902,NaN,NaN
top,NaN,Fabiana Ramos,21/03/1988,"8122,61",NaN,FALSO,MS,sem email,"710,728375","676,8841667","4439,17",NaN,NaN
freq,NaN,27,12,3,NaN,25027,1911,23976,3,3,4,NaN,NaN
mean,24999.500000,NaN,NaN,NaN,2.506663,NaN,NaN,NaN,NaN,NaN,NaN,601.599704,16.825000
std,14433.901067,NaN,NaN,NaN,1.713125,NaN,NaN,NaN,NaN,NaN,NaN,336.461427,62.635835
min,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,225.000000,0.000000
25%,12499.750000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,225.000000,0.000000
50%,24999.500000,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,675.000000,0.000000
75%,37499.250000,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,900.000000,0.000000
max,49999.000000,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,1125.000000,250.000000

In [182]:
# Consigo aplicar uma função a linhas e colunas de um dataframe
# -------------------------------------------------------------
# Quero saber o tipo da coluna 'Nome' => type(var)
# -------------------------------------------------------------

print(df_folha['Nome'].head().apply(type))

0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
Name: Nome, dtype: object

In [183]:
df_folha['Nome'] = df_folha['Nome'].astype(str) # sem efeito, mesmo contendo NaN

In [184]:
print(df_folha['Nome'].head().apply(type))

0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
Name: Nome, dtype: object

In [185]:
df_folha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Indice         50000 non-null  int64
 1   Nome           50000 non-null  object
 2   Nascimento     49970 non-null  object
 3   Salï¿½rio      49972 non-null  object
 4   Filhos         49978 non-null  float64
 5   Ativo          49976 non-null  object
 6   UF             49971 non-null  object
 7   email          49964 non-null  object
 8   FGTS           49972 non-null  object
 9   13Sal          49972 non-null  object
 10  Fï¿½rias       49972 non-null  object
 11  CestaBï¿½sica  49978 non-null  float64
 12  AjudaCusto     50000 non-null  int64
dtypes: float64(2), int64(2), object(9)
memory usage: 5.0+ MB

In [186]:
print(df_folha['Nascimento'].head().apply(type))

0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
Name: Nascimento, dtype: object

In [187]:
df_folha[df_folha['Nascimento']>='01/01/1991'].head()

,Indice,Nome,Nascimento,Salï¿½rio,Filhos,Ativo,UF,email,FGTS,13Sal,Fï¿½rias,CestaBï¿½sica,AjudaCusto
0,0,Zacarias Vieira,30/04/1967,"6873,72",2.0,VERDADEIRO,MS,sem email,"601,4505","572,81","2291,24",450.0,0
1,1,Ana da Gomes,08/08/1966,"10744,1",5.0,VERDADEIRO,MG,sem email,"940,10875","895,3416667","3581,37",1125.0,0
2,2,Bruno Cardoso Filha,04/12/1989,"14647,7",3.0,VERDADEIRO,BA,nï¿½o confirmado,"1281,67375","1220,641667","4882,57",675.0,0
3,3,Joï¿½o Martins,22/05/1953,"7819,52",5.0,FALSO,RN,sem email,"684,208","651,6266667","2606,51",1125.0,0
4,4,Carla Martins,19/05/1984,"17444,58",0.0,FALSO,PE,sem email,"1526,40075","1453,715","5814,86",225.0,0

In [84]:
df_folha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Indice         50000 non-null  int64
 1   Nome           50000 non-null  object
 2   Nascimento     49970 non-null  object
 3   Salï¿½rio      49972 non-null  object
 4   Filhos         49978 non-null  float64
 5   Ativo          49976 non-null  object
 6   UF             49971 non-null  object
 7   email          49964 non-null  object
 8   FGTS           49972 non-null  object
 9   13Sal          49972 non-null  object
 10  Fï¿½rias       49972 non-null  object
 11  CestaBï¿½sica  49978 non-null  float64
 12  AjudaCusto     50000 non-null  int64
dtypes: float64(2), int64(2), object(9)
memory usage: 5.0+ MB

In [188]:
df_folha['Nascimento'] = pd.to_datetime(df_folha['Nascimento'], format='%d/%m/%Y')

In [189]:
print(df_folha['Nascimento'].head().apply(type))

0    <class 'pandas._libs.tslibs.timestamps.Timesta...
1    <class 'pandas._libs.tslibs.timestamps.Timesta...
2    <class 'pandas._libs.tslibs.timestamps.Timesta...
3    <class 'pandas._libs.tslibs.timestamps.Timesta...
4    <class 'pandas._libs.tslibs.timestamps.Timesta...
Name: Nascimento, dtype: object

In [190]:
df_folha.head()

,Indice,Nome,Nascimento,Salï¿½rio,Filhos,Ativo,UF,email,FGTS,13Sal,Fï¿½rias,CestaBï¿½sica,AjudaCusto
0,0,Zacarias Vieira,1967-04-30,"6873,72",2.0,VERDADEIRO,MS,sem email,"601,4505","572,81","2291,24",450.0,0
1,1,Ana da Gomes,1966-08-08,"10744,1",5.0,VERDADEIRO,MG,sem email,"940,10875","895,3416667","3581,37",1125.0,0
2,2,Bruno Cardoso Filha,1989-12-04,"14647,7",3.0,VERDADEIRO,BA,nï¿½o confirmado,"1281,67375","1220,641667","4882,57",675.0,0
3,3,Joï¿½o Martins,1953-05-22,"7819,52",5.0,FALSO,RN,sem email,"684,208","651,6266667","2606,51",1125.0,0
4,4,Carla Martins,1984-05-19,"17444,58",0.0,FALSO,PE,sem email,"1526,40075","1453,715","5814,86",225.0,0

Quando você usa a função pd.to_datetime() com o argumento format='%d/%m/%Y', o pandas converte as strings da coluna especificada para o tipo datetime, adotando o formato padrão ISO 8601 para representar datas, que é YYYY-MM-DD. Por isso, após a conversão, as datas aparecem no formato 1967-04-30, por exemplo, mesmo que originalmente estivessem em um formato diferente, como 30/04/1967.

In [191]:
df_folha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Indice         50000 non-null  int64
 1   Nome           50000 non-null  object
 2   Nascimento     49970 non-null  datetime64[ns]
 3   Salï¿½rio      49972 non-null  object
 4   Filhos         49978 non-null  float64
 5   Ativo          49976 non-null  object
 6   UF             49971 non-null  object
 7   email          49964 non-null  object
 8   FGTS           49972 non-null  object
 9   13Sal          49972 non-null  object
 10  Fï¿½rias       49972 non-null  object
 11  CestaBï¿½sica  49978 non-null  float64
 12  AjudaCusto     50000 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(2), object(8)
memory usage: 5.0+ MB

In [192]:
# Criar um colunha com a string data formatda
# -------------------------------------------
df_folha['Nascimento_formatado'] = df_folha['Nascimento'].dt.strftime('%d/%m/%Y')

In [193]:
df_folha['Nascimento_formatado'].head()

0    30/04/1967
1    08/08/1966
2    04/12/1989
3    22/05/1953
4    19/05/1984
Name: Nascimento_formatado, dtype: object

In [40]:
df_folha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Indice                50000 non-null  int64
 1   Nome                  49969 non-null  object
 2   Nascimento            49970 non-null  datetime64[ns]
 3   Salï¿½rio             49972 non-null  object
 4   Filhos                49978 non-null  float64
 5   Ativo                 49976 non-null  object
 6   UF                    49971 non-null  object
 7   email                 49964 non-null  object
 8   FGTS                  49972 non-null  object
 9   13Sal                 49972 non-null  object
 10  Fï¿½rias              49972 non-null  object
 11  CestaBï¿½sica         49978 non-null  float64
 12  AjudaCusto            50000 non-null  int64
 13  Nascimento_formatado  49970 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 5.3+ MB

datetime[ns] é um tipo de dados utilizado pelo pandas para representar datas e horas com precisão de nanossegundos. A sigla ns refere-se a nanossegundos, onde um nanossegundo é um bilionésimo de segundo (1 segundo = 1.000.000.000 nanossegundos). Esse tipo de dados é especialmente útil para manipulação de séries temporais em análises financeiras, científicas, ou qualquer outro domínio onde a precisão temporal em alta resolução é necessária.

Características de datetime[ns]
Alta Precisão: O uso de nanossegundos permite uma representação muito precisa de timestamps, útil para dados que requerem marcações temporais detalhadas, como transações financeiras ou eventos em sistemas de alta frequência.

Compatibilidade com NumPy: Pandas utiliza o NumPy por baixo dos panos, que suporta datetime64[ns]. Isso permite integração e operações eficientes com arrays de NumPy e facilita a manipulação de dados temporais em larga escala.

Operações Temporais: Com o tipo datetime[ns], pandas permite realizar operações como diferenças de tempo, resampling (reagrupamento de dados temporais), shifting (deslocamento de dados no tempo), entre outras, com facilidade e precisão.

In [194]:
print(df_folha['Salï¿½rio'].head().apply(type))

0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
Name: Salï¿½rio, dtype: object

In [195]:
df_folha.rename(columns={'Salï¿½rio': 'Salario'}, inplace=True)

df_folha['Salario'] = df_folha['Salario'].str.replace(',', '.').astype(float)

In [196]:
df_folha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Indice                50000 non-null  int64
 1   Nome                  50000 non-null  object
 2   Nascimento            49970 non-null  datetime64[ns]
 3   Salario               49972 non-null  float64
 4   Filhos                49978 non-null  float64
 5   Ativo                 49976 non-null  object
 6   UF                    49971 non-null  object
 7   email                 49964 non-null  object
 8   FGTS                  49972 non-null  object
 9   13Sal                 49972 non-null  object
 10  Fï¿½rias              49972 non-null  object
 11  CestaBï¿½sica         49978 non-null  float64
 12  AjudaCusto            50000 non-null  int64
 13  Nascimento_formatado  49970 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(2), object(8)
memory usage: 5.3+ MB

In [198]:
df_folha['Salario'].head(500)

0       6873.72
1      10744.10
2      14647.70
3       7819.52
4      17444.58
         ...
495     1670.86
496    13131.26
497    11300.17
498    17322.04
499    11744.58
Name: Salario, Length: 500, dtype: float64

In [199]:
print(df_folha['Filhos'].head().apply(type))

0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
Name: Filhos, dtype: object

In [200]:
df_folha['Filhos'] = df_folha['Filhos'].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [201]:
# NaN (not a number)
# NaT (not a datetime)
# Preencher NaN com 0
# -----------------------------------------------------
df_folha['Filhos'] = df_folha['Filhos'].fillna(0)
df_folha['Filhos'] = df_folha['Filhos'].astype('Int64')

In [202]:
df_folha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Indice                50000 non-null  int64
 1   Nome                  50000 non-null  object
 2   Nascimento            49970 non-null  datetime64[ns]
 3   Salario               49972 non-null  float64
 4   Filhos                50000 non-null  Int64
 5   Ativo                 49976 non-null  object
 6   UF                    49971 non-null  object
 7   email                 49964 non-null  object
 8   FGTS                  49972 non-null  object
 9   13Sal                 49972 non-null  object
 10  Fï¿½rias              49972 non-null  object
 11  CestaBï¿½sica         49978 non-null  float64
 12  AjudaCusto            50000 non-null  int64
 13  Nascimento_formatado  49970 non-null  object
dtypes: Int64(1), datetime64[ns](1), float64(2), int64(2), object(8)
memory usage: 5.4+ MB

In [204]:
df_folha.head(100)

,Indice,Nome,Nascimento,Salario,Filhos,Ativo,UF,email,FGTS,13Sal,Fï¿½rias,CestaBï¿½sica,AjudaCusto,Nascimento_formatado
0,0,Zacarias Vieira,1967-04-30,6873.72,2,VERDADEIRO,MS,sem email,"601,4505","572,81","2291,24",450.0,0,30/04/1967
1,1,Ana da Gomes,1966-08-08,10744.10,5,VERDADEIRO,MG,sem email,"940,10875","895,3416667","3581,37",1125.0,0,08/08/1966
2,2,Bruno Cardoso Filha,1989-12-04,14647.70,3,VERDADEIRO,BA,nï¿½o confirmado,"1281,67375","1220,641667","4882,57",675.0,0,04/12/1989
3,3,Joï¿½o Martins,1953-05-22,7819.52,5,FALSO,RN,sem email,"684,208","651,6266667","2606,51",1125.0,0,22/05/1953
4,4,Carla Martins,1984-05-19,17444.58,0,FALSO,PE,sem email,"1526,40075","1453,715","5814,86",225.0,0,19/05/1984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,Vitor Ferreira Filha,1955-08-11,10657.24,0,FALSO,BA,invalido,"932,5085","888,1033333","3552,41",225.0,0,11/08/1955
96,96,Mariana Lopes,1986-08-15,13301.27,5,VERDADEIRO,MA,nï¿½o confirmado,"1163,861125","1108,439167","4433,76",1125.0,0,15/08/1986
97,97,Oscar Martins,1988-02-23,7812.06,4,FALSO,ES,invalido,"683,55525","651,005","2604,02",900.0,0,23/02/1988
98,98,Olï¿½via Gonï¿½alves,1988-11-10,2383.29,1,FALSO,RS,invalido,"208,537875","198,6075","794,43",225.0,250,10/11/1988
99,99,Wesley Lopes,1972-02-09,3613.08,0,VERDADEIRO,GO,invalido,"316,1445","301,09","1204,36",225.0,0,09/02/1972

In [205]:
print(df_folha['Ativo'].head().apply(type))

0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
Name: Ativo, dtype: object

In [206]:
tem_nan = df_folha['Ativo'].isna().any()
print(tem_nan)
print(df_folha['Ativo'].head().apply(type))

True
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
Name: Ativo, dtype: object

In [207]:
df_folha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Indice                50000 non-null  int64
 1   Nome                  50000 non-null  object
 2   Nascimento            49970 non-null  datetime64[ns]
 3   Salario               49972 non-null  float64
 4   Filhos                50000 non-null  Int64
 5   Ativo                 49976 non-null  object
 6   UF                    49971 non-null  object
 7   email                 49964 non-null  object
 8   FGTS                  49972 non-null  object
 9   13Sal                 49972 non-null  object
 10  Fï¿½rias              49972 non-null  object
 11  CestaBï¿½sica         49978 non-null  float64
 12  AjudaCusto            50000 non-null  int64
 13  Nascimento_formatado  49970 non-null  object
dtypes: Int64(1), datetime64[ns](1), float64(2), int64(2), object(8)
memory usage: 5.4+ MB

In [208]:
# ------------------------------------------------------------------------------------------------------------------------+
# A função map é usada em diferentes contextos em Python, mas geralmente serve para aplicar uma função a cada item
# de um iterável (como uma lista) e retornar um novo iterável com os resultados. No contexto do pandas, map é um método
# disponível para objetos do tipo Series, e é usado para mapear os valores de uma série de acordo com um dicionário,
# uma série ou uma função. Usando um Dicionário: Você pode passar um dicionário ao map onde as chaves são os valores 
# atuais na série e os valores do dicionário são os novos valores para esses elementos.
# ------------------------------------------------------------------------------------------------------------------------+

df_folha['Ativo'] = df_folha['Ativo'].map({'VERDADEIRO': True, 'FALSO': False})

print(df_folha['Ativo'].dtype)

print(df_folha['Ativo'].head().apply(type))

object
0    <class 'bool'>
1    <class 'bool'>
2    <class 'bool'>
3    <class 'bool'>
4    <class 'bool'>
Name: Ativo, dtype: object

In [209]:
df_folha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Indice                50000 non-null  int64
 1   Nome                  50000 non-null  object
 2   Nascimento            49970 non-null  datetime64[ns]
 3   Salario               49972 non-null  float64
 4   Filhos                50000 non-null  Int64
 5   Ativo                 49976 non-null  object
 6   UF                    49971 non-null  object
 7   email                 49964 non-null  object
 8   FGTS                  49972 non-null  object
 9   13Sal                 49972 non-null  object
 10  Fï¿½rias              49972 non-null  object
 11  CestaBï¿½sica         49978 non-null  float64
 12  AjudaCusto            50000 non-null  int64
 13  Nascimento_formatado  49970 non-null  object
dtypes: Int64(1), datetime64[ns](1), float64(2), int64(2), object(8)
memory usage: 5.4+ MB

In [211]:
df_folha.head(49500)

,Indice,Nome,Nascimento,Salario,Filhos,Ativo,UF,email,FGTS,13Sal,Fï¿½rias,CestaBï¿½sica,AjudaCusto,Nascimento_formatado
0,0,Zacarias Vieira,1967-04-30,6873.72,2,True,MS,sem email,"601,4505","572,81","2291,24",450.0,0,30/04/1967
1,1,Ana da Gomes,1966-08-08,10744.10,5,True,MG,sem email,"940,10875","895,3416667","3581,37",1125.0,0,08/08/1966
2,2,Bruno Cardoso Filha,1989-12-04,14647.70,3,True,BA,nï¿½o confirmado,"1281,67375","1220,641667","4882,57",675.0,0,04/12/1989
3,3,Joï¿½o Martins,1953-05-22,7819.52,5,False,RN,sem email,"684,208","651,6266667","2606,51",1125.0,0,22/05/1953
4,4,Carla Martins,1984-05-19,17444.58,0,False,PE,sem email,"1526,40075","1453,715","5814,86",225.0,0,19/05/1984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49495,49495,Patrï¿½cia Moura,1980-11-04,12269.38,0,False,RJ,invalido,"1073,57075","1022,448333","4089,79",225.0,0,04/11/1980
49496,49496,Larissa Ramos,1984-07-19,10777.92,3,True,MG,nï¿½o confirmado,"943,068","898,16","3592,64",675.0,0,19/07/1984
49497,49497,Xuxa Lima,1992-05-08,17513.84,0,False,MA,nï¿½o confirmado,"1532,461","1459,486667","5837,95",225.0,0,08/05/1992
49498,49498,Tiago Ribeiro,1979-11-29,17030.36,4,False,CE,sem email,"1490,1565","1419,196667","5676,79",900.0,0,29/11/1979
49499,49499,Patrï¿½cia Silva,1962-06-02,11045.05,1,True,DF,invalido,"966,441875","920,4208333","3681,68",225.0,0,02/06/1962

In [126]:
df_folha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Indice         50000 non-null  int64
 1   Nome           50000 non-null  object
 2   Nascimento     49970 non-null  datetime64[ns]
 3   Salário        49972 non-null  float64
 4   Filhos         50000 non-null  Int64
 5   Ativo          49976 non-null  object
 6   UF             49971 non-null  object
 7   email          49964 non-null  object
 8   FGTS           49972 non-null  object
 9   13Sal          49972 non-null  object
 10  Fï¿½rias       49972 non-null  object
 11  CestaBï¿½sica  49978 non-null  float64
 12  AjudaCusto     50000 non-null  int64
dtypes: Int64(1), datetime64[ns](1), float64(2), int64(2), object(7)
memory usage: 5.0+ MB

O pandas possui tipos de dados opcionais (Nullable) para booleanos e inteiros que podem incluir NaN enquanto mantêm seu tipo específico. Tipo boolean (pd.BooleanDtype()), você pode converter explicitamente a coluna para esse tipo para manter NaN e valores

In [212]:
print(df_folha['Ativo'].head().apply(type))

0    <class 'bool'>
1    <class 'bool'>
2    <class 'bool'>
3    <class 'bool'>
4    <class 'bool'>
Name: Ativo, dtype: object

In [213]:
df_folha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Indice                50000 non-null  int64
 1   Nome                  50000 non-null  object
 2   Nascimento            49970 non-null  datetime64[ns]
 3   Salario               49972 non-null  float64
 4   Filhos                50000 non-null  Int64
 5   Ativo                 49976 non-null  object
 6   UF                    49971 non-null  object
 7   email                 49964 non-null  object
 8   FGTS                  49972 non-null  object
 9   13Sal                 49972 non-null  object
 10  Fï¿½rias              49972 non-null  object
 11  CestaBï¿½sica         49978 non-null  float64
 12  AjudaCusto            50000 non-null  int64
 13  Nascimento_formatado  49970 non-null  object
dtypes: Int64(1), datetime64[ns](1), float64(2), int64(2), object(8)
memory usage: 5.4+ MB

In [216]:
# Sem efeito de transformação ou necessidade
# ------------------------------------------

df_folha['UF']    = df_folha['UF'].astype(str)

df_folha['email'] = df_folha['email'].astype(str)

In [214]:
print(df_folha['UF'].head().apply(type))

0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
Name: UF, dtype: object

In [215]:
print(df_folha['email'].head().apply(type))

0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
Name: email, dtype: object

In [58]:
df_folha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Indice                50000 non-null  int64
 1   Nome                  49969 non-null  object
 2   Nascimento            49970 non-null  datetime64[ns]
 3   Salário               49972 non-null  float64
 4   Filhos                50000 non-null  Int64
 5   Ativo                 49976 non-null  object
 6   UF                    50000 non-null  object
 7   email                 50000 non-null  object
 8   FGTS                  49972 non-null  object
 9   13Sal                 49972 non-null  object
 10  Fï¿½rias              49972 non-null  object
 11  CestaBï¿½sica         49978 non-null  float64
 12  AjudaCusto            50000 non-null  int64
 13  Nascimento_formatado  49970 non-null  object
dtypes: Int64(1), datetime64[ns](1), float64(2), int64(2), object(8)
memory usage: 5.4+ MB

In [59]:
df_folha.head(500)

,Indice,Nome,Nascimento,Salário,Filhos,Ativo,UF,email,FGTS,13Sal,Fï¿½rias,CestaBï¿½sica,AjudaCusto,Nascimento_formatado
0,0,Zacarias Vieira,1967-04-30,6873.72,2,True,MS,sem email,"601,4505","572,81","2291,24",450.0,0,30/04/1967
1,1,Ana da Gomes,1966-08-08,10744.10,5,True,MG,sem email,"940,10875","895,3416667","3581,37",1125.0,0,08/08/1966
2,2,Bruno Cardoso Filha,1989-12-04,14647.70,3,True,BA,nï¿½o confirmado,"1281,67375","1220,641667","4882,57",675.0,0,04/12/1989
3,3,Joï¿½o Martins,1953-05-22,7819.52,5,False,RN,sem email,"684,208","651,6266667","2606,51",1125.0,0,22/05/1953
4,4,Carla Martins,1984-05-19,17444.58,0,False,PE,sem email,"1526,40075","1453,715","5814,86",225.0,0,19/05/1984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,Daniela Andrade,1983-11-21,1670.86,2,True,ES,sem email,"146,20025","139,2383333","556,95",450.0,250,21/11/1983
496,496,Oscar dos Silva,1987-05-07,13131.26,3,False,MA,sem email,"1148,98525","1094,271667","4377,09",675.0,0,07/05/1987
497,497,Carla dos Costa,1960-10-30,11300.17,4,True,GO,invalido,"988,764875","941,6808333","3766,72",900.0,0,30/10/1960
498,498,Sandra Borges,1971-06-12,17322.04,1,False,BA,spamlistafirewall,"1515,6785","1443,503333","5774,01",225.0,0,12/06/1971
499,499,Valentina Lopes,1966-07-16,11744.58,4,True,SP,sem email,"1027,65075","978,715","3914,86",900.0,0,16/07/1966

In [217]:
print(df_folha['FGTS'].head().apply(type))

0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
Name: FGTS, dtype: object

In [218]:
df_folha['FGTS'] = df_folha['FGTS'].str.replace(',', '.').fillna('0').astype(float).round(2)

In [220]:
print(df_folha['FGTS'].head().apply(type))

0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
Name: FGTS, dtype: object

In [219]:
df_folha.head()

,Indice,Nome,Nascimento,Salario,Filhos,Ativo,UF,email,FGTS,13Sal,Fï¿½rias,CestaBï¿½sica,AjudaCusto,Nascimento_formatado
0,0,Zacarias Vieira,1967-04-30,6873.72,2,True,MS,sem email,601.45,"572,81","2291,24",450.0,0,30/04/1967
1,1,Ana da Gomes,1966-08-08,10744.10,5,True,MG,sem email,940.11,"895,3416667","3581,37",1125.0,0,08/08/1966
2,2,Bruno Cardoso Filha,1989-12-04,14647.70,3,True,BA,nï¿½o confirmado,1281.67,"1220,641667","4882,57",675.0,0,04/12/1989
3,3,Joï¿½o Martins,1953-05-22,7819.52,5,False,RN,sem email,684.21,"651,6266667","2606,51",1125.0,0,22/05/1953
4,4,Carla Martins,1984-05-19,17444.58,0,False,PE,sem email,1526.40,"1453,715","5814,86",225.0,0,19/05/1984

In [221]:
df_folha.rename(columns={'13Sal': 'decimo_terceiro'}, inplace=True)

df_folha['decimo_terceiro'] = df_folha['decimo_terceiro'].str.replace(',', '.').fillna('0').astype(float).round(2)

In [222]:
df_folha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Indice                50000 non-null  int64
 1   Nome                  50000 non-null  object
 2   Nascimento            49970 non-null  datetime64[ns]
 3   Salario               49972 non-null  float64
 4   Filhos                50000 non-null  Int64
 5   Ativo                 49976 non-null  object
 6   UF                    50000 non-null  object
 7   email                 50000 non-null  object
 8   FGTS                  50000 non-null  float64
 9   decimo_terceiro       50000 non-null  float64
 10  Fï¿½rias              49972 non-null  object
 11  CestaBï¿½sica         49978 non-null  float64
 12  AjudaCusto            50000 non-null  int64
 13  Nascimento_formatado  49970 non-null  object
dtypes: Int64(1), datetime64[ns](1), float64(4), int64(2), object(6)
memory usage: 5.4+ MB

In [223]:
df_folha.head()

,Indice,Nome,Nascimento,Salario,Filhos,Ativo,UF,email,FGTS,decimo_terceiro,Fï¿½rias,CestaBï¿½sica,AjudaCusto,Nascimento_formatado
0,0,Zacarias Vieira,1967-04-30,6873.72,2,True,MS,sem email,601.45,572.81,"2291,24",450.0,0,30/04/1967
1,1,Ana da Gomes,1966-08-08,10744.10,5,True,MG,sem email,940.11,895.34,"3581,37",1125.0,0,08/08/1966
2,2,Bruno Cardoso Filha,1989-12-04,14647.70,3,True,BA,nï¿½o confirmado,1281.67,1220.64,"4882,57",675.0,0,04/12/1989
3,3,Joï¿½o Martins,1953-05-22,7819.52,5,False,RN,sem email,684.21,651.63,"2606,51",1125.0,0,22/05/1953
4,4,Carla Martins,1984-05-19,17444.58,0,False,PE,sem email,1526.40,1453.72,"5814,86",225.0,0,19/05/1984

Um lambda no Python é basicamente uma forma curta de definir uma função anônima, ou seja, uma função sem nome. Ela pode ter qualquer número de argumentos, mas só pode ter uma expressão. Lambdas são úteis quando você precisa de uma função simples para uma operação de curta duração e não quer formalmente defini-la com o def.

In [226]:
quadrado_lambda = lambda num: num ** 2
print(quadrado_lambda(11))

121

A função map aplica uma função especificada a cada item de um iterável (como uma lista) e retorna um novo iterável com os resultados. map é comumente usado quando você quer transformar os dados de uma forma para outra.

In [228]:
numeros   = [1, 2, 3, 4, 5]
quadrados = list(map(lambda num: num ** 3, numeros))
print(quadrados)

[1, 8, 27, 64, 125]

A função filter aplica uma função especificada, que deve retornar True ou False, a cada item de um iterável. filter retorna um novo iterável contendo apenas os itens para os quais a função aplicada retorna True. É útil quando você precisa filtrar um conjunto de dados de acordo com algum critério.

In [230]:
numeros = [1, 2, 3, 4, 5]
maiores_que_dois = list(filter(lambda num: num >= 2, numeros))
print(maiores_que_dois)

[2, 3, 4, 5]

In [231]:
df_folha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Indice                50000 non-null  int64
 1   Nome                  50000 non-null  object
 2   Nascimento            49970 non-null  datetime64[ns]
 3   Salario               49972 non-null  float64
 4   Filhos                50000 non-null  Int64
 5   Ativo                 49976 non-null  object
 6   UF                    50000 non-null  object
 7   email                 50000 non-null  object
 8   FGTS                  50000 non-null  float64
 9   decimo_terceiro       50000 non-null  float64
 10  Fï¿½rias              49972 non-null  object
 11  CestaBï¿½sica         49978 non-null  float64
 12  AjudaCusto            50000 non-null  int64
 13  Nascimento_formatado  49970 non-null  object
dtypes: Int64(1), datetime64[ns](1), float64(4), int64(2), object(6)
memory usage: 5.4+ MB

In [232]:
def ajusta_virgula(coluna):
    
    if pd.isna(coluna):
        return 0
    
    elif isinstance(coluna, str):
        try:
            return float(coluna.replace(',', '.'))
        except ValueError:
            return 0
    
    else:
        return coluna

ajusta_colunas = ['Fï¿½rias', 'CestaBï¿½sica', 'AjudaCusto']

for coluna in ajusta_colunas:
    df_folha[coluna] = df_folha[coluna].apply(lambda x: ajusta_virgula(x))

df_folha.rename(columns={'Fï¿½rias': 'Ferias', 'CestaBï¿½sica': 'CestaBasica'}, inplace=True)

In [233]:
df_folha.head()

,Indice,Nome,Nascimento,Salario,Filhos,Ativo,UF,email,FGTS,decimo_terceiro,Ferias,CestaBasica,AjudaCusto,Nascimento_formatado
0,0,Zacarias Vieira,1967-04-30,6873.72,2,True,MS,sem email,601.45,572.81,2291.24,450.0,0,30/04/1967
1,1,Ana da Gomes,1966-08-08,10744.10,5,True,MG,sem email,940.11,895.34,3581.37,1125.0,0,08/08/1966
2,2,Bruno Cardoso Filha,1989-12-04,14647.70,3,True,BA,nï¿½o confirmado,1281.67,1220.64,4882.57,675.0,0,04/12/1989
3,3,Joï¿½o Martins,1953-05-22,7819.52,5,False,RN,sem email,684.21,651.63,2606.51,1125.0,0,22/05/1953
4,4,Carla Martins,1984-05-19,17444.58,0,False,PE,sem email,1526.40,1453.72,5814.86,225.0,0,19/05/1984

In [234]:
df_folha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Indice                50000 non-null  int64
 1   Nome                  50000 non-null  object
 2   Nascimento            49970 non-null  datetime64[ns]
 3   Salario               49972 non-null  float64
 4   Filhos                50000 non-null  Int64
 5   Ativo                 49976 non-null  object
 6   UF                    50000 non-null  object
 7   email                 50000 non-null  object
 8   FGTS                  50000 non-null  float64
 9   decimo_terceiro       50000 non-null  float64
 10  Ferias                50000 non-null  float64
 11  CestaBasica           50000 non-null  float64
 12  AjudaCusto            50000 non-null  int64
 13  Nascimento_formatado  49970 non-null  object
dtypes: Int64(1), datetime64[ns](1), float64(5), int64(2), object(5)
memory usage: 5.4+ MB

In [236]:
# Lista das colunas desejadas

colunas_selecionadas = [
    'Nome', 'Nascimento', 'Salario', 'Filhos', 'Ativo', 'UF', 'email', 
    'FGTS', 'decimo_terceiro', 'Ferias', 'CestaBasica', 'AjudaCusto'
]

df_folha = df_folha[colunas_selecionadas]

In [237]:
df_folha.head()

,Nome,Nascimento,Salario,Filhos,Ativo,UF,email,FGTS,decimo_terceiro,Ferias,CestaBasica,AjudaCusto
0,Zacarias Vieira,1967-04-30,6873.72,2,True,MS,sem email,601.45,572.81,2291.24,450.0,0
1,Ana da Gomes,1966-08-08,10744.10,5,True,MG,sem email,940.11,895.34,3581.37,1125.0,0
2,Bruno Cardoso Filha,1989-12-04,14647.70,3,True,BA,nï¿½o confirmado,1281.67,1220.64,4882.57,675.0,0
3,Joï¿½o Martins,1953-05-22,7819.52,5,False,RN,sem email,684.21,651.63,2606.51,1125.0,0
4,Carla Martins,1984-05-19,17444.58,0,False,PE,sem email,1526.40,1453.72,5814.86,225.0,0

In [239]:
df_folha[(df_folha['Salario']>=3000) & (df_folha['Filhos']==3)].head(100)

,Nome,Nascimento,Salario,Filhos,Ativo,UF,email,FGTS,decimo_terceiro,Ferias,CestaBasica,AjudaCusto
2,Bruno Cardoso Filha,1989-12-04,14647.70,3,True,BA,nï¿½o confirmado,1281.67,1220.64,4882.57,675.0,0
5,Alice Freitas,1988-10-16,12480.39,3,True,MA,sem email,1092.03,1040.03,4160.13,675.0,0
18,Leonardo Borges,1977-01-29,4246.73,3,False,PB,invalido,371.59,353.89,1415.58,675.0,0
25,Olï¿½via Rodrigues,1974-10-12,8058.25,3,True,SC,sem email,705.10,671.52,2686.08,675.0,0
32,Yara Monteiro,1965-02-23,3862.66,3,False,RS,sem email,337.98,321.89,1287.55,675.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
586,Marcos Moura,1974-12-30,16097.83,3,True,AM,nï¿½o confirmado,1408.56,1341.49,5365.94,675.0,0
609,Wesley Castro,1992-07-03,17617.56,3,False,SE,invalido,1541.54,1468.13,5872.52,675.0,0
612,Sofia Martins,1952-08-16,15907.36,3,False,SE,sem email,1391.89,1325.61,5302.45,675.0,0
620,Leonardo Castro,1997-01-20,15678.76,3,True,DF,sem email,1371.89,1306.56,5226.25,675.0,0
632,Sandra das Castro,1951-05-03,3199.74,3,True,DF,sem email,279.98,266.64,1066.58,675.0,0

In [252]:
# ----------------------------------------------------------------------------------------------------------------------- #
# Seleção de dados no dataframe
# ----------------------------------------------------------------------------------------------------------------------- #
filtro = ( df_folha['Salario'] >= 12000)             & \
         ( df_folha['Filhos'] == 3)                  & \
         ( df_folha['UF'].isin(['SE', 'MA', 'SP']) ) & \
         ( df_folha['Ativo'] )

print("Registros : ",df_folha[filtro].shape[0])

df_folha[filtro].head(100)

Registros :  129

,Nome,Nascimento,Salario,Filhos,Ativo,UF,email,FGTS,decimo_terceiro,Ferias,CestaBasica,AjudaCusto
5,Alice Freitas,1988-10-16,12480.39,3,True,MA,sem email,1092.03,1040.03,4160.13,675.0,0
254,Irene Carneiro Sobrinha,1963-12-18,17072.52,3,True,SE,sem email,1493.85,1422.71,5690.84,675.0,0
314,Bruno Carneiro,1963-04-05,18730.73,3,True,MA,invalido,1638.94,1560.89,6243.58,675.0,0
559,Camila Melo,1962-06-12,18589.02,3,True,MA,invalido,1626.54,1549.08,6196.34,675.0,0
900,Mariana Martinez Filho,1971-09-19,17398.57,3,True,MA,invalido,1522.37,1449.88,5799.52,675.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
35915,Irene Lopes,1980-01-25,18624.71,3,True,SE,sem email,1629.66,1552.06,6208.24,675.0,0
37826,Roberto Monteiro,1995-03-12,15657.95,3,True,MA,nï¿½o confirmado,1370.07,1304.83,5219.32,675.0,0
38106,Xuxa Andrade,1957-03-13,18178.21,3,True,MA,sem email,1590.59,1514.85,6059.40,675.0,0
38404,Tiago das Melo,1953-05-02,15668.17,3,True,MA,invalido,1370.96,1305.68,5222.72,675.0,0
38511,Eduardo Andrade,1999-01-06,15466.63,3,True,MA,nï¿½o confirmado,1353.33,1288.89,5155.54,675.0,0

O termo axis (eixo) em bibliotecas de manipulação de dados como pandas e numpy refere-se à direção ao longo da qual uma operação é realizada em uma estrutura de dados. Em estruturas de dados multidimensionais como DataFrames (pandas) e arrays (numpy), axis ajuda a especificar se você deseja realizar uma operação ao longo das linhas ou colunas (ou em outras dimensões, no caso de arrays com mais de duas dimensões).

In [249]:
tem_nan_linhas = df_folha.isna().any(axis=1).any()

print(tem_nan_linhas)

True

In [250]:
tem_nan_colunas = df_folha.isna().any(axis=0)

print(tem_nan_colunas)

Nome               False
Nascimento          True
Salario             True
Filhos             False
Ativo               True
UF                 False
email              False
FGTS               False
decimo_terceiro    False
Ferias             False
CestaBasica        False
AjudaCusto         False
dtype: bool

In [251]:
caracteres_validos = r'[^a-záàéèíìóòúùA-ZÁÀÉÈÍÌÓÒÚÙçÇ@,.-0-9]'

mascara            = df_folha.applymap(lambda x: bool(re.search(caracteres_validos, str(x))))

linhas_com_caractere_especial = mascara.any(axis=1).sum()
colunas_com_caractere_especial = mascara.any().sum()

print(f'Linhas com caractere especial: {linhas_com_caractere_especial}')
print(f'Colunas com caractere especial: {colunas_com_caractere_especial}')

Linhas com caractere especial: 50000
Colunas com caractere especial: 10

:: --------------------------------------------------------------------------------------------------------------------- ::
:: Exercicio Proposto
:: Analisando o contexto, o código e o resultado, podemos dizer que está correto?
:: --------------------------------------------------------------------------------------------------------------------- ::

applymap(lambda x: bool(re.search(caracteres_validos, str(x)))): Aplica uma função a cada elemento do DataFrame que verifica se o elemento contém qualquer caractere fora do conjunto definido de caracteres válidos. Isso cria uma máscara booleana onde True indica a presença de um caractere especial.

mascara.any(axis=1).sum(): Calcula o número de linhas que contêm pelo menos um True na máscara booleana, ou seja, pelo menos um caractere especial.

mascara.any().sum(): Calcula o número de colunas que contêm pelo menos um True.

In [ ]:
# ----------------------------------------------------------------------------------------------------------------------- #
# Exercício Proposto
# Construa em um único script toda transforamção de tipos de dados do dataframe df_folha
# ----------------------------------------------------------------------------------------------------------------------- #

import pandas as pd
import numpy  as np

df_dados = pd.read_csv("FolhaPag.csv", delimiter=';', encoding='Windows-1252')

df_folha = df_dados.copy()

In [ ]:
# Exercício Proposto
# Alterar a coluna AjudaCusto => float
# --------------------------------------------------------------------------------------